/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_USERMODE 1
#undef  CONFIG_ISA
#undef  CONFIG_SBUS
#undef  CONFIG_PCI
#define CONFIG_UID16 1
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1

/*
 * General Setup
 */
#define CONFIG_STDIO_CONSOLE 1
#define CONFIG_NET 1
#define CONFIG_SYSVIPC 1
#define CONFIG_BSD_PROCESS_ACCT 1
#define CONFIG_SYSCTL 1
#define CONFIG_VMS 1
#define CONFIG_IO_VMS 1
#define CONFIG_MM_VMS 1
#define CONFIG_EXTTWO_FS 1
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_PROC_FS 1
#define CONFIG_DEVFS_FS 1
#define CONFIG_DEVFS_MOUNT 1
#define CONFIG_DEVPTS_FS 1
#define CONFIG_BINFMT_AOUT 1
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC 1
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_UNIX98_PTY_COUNT (256)
#define CONFIG_SSL 1
#define CONFIG_HOSTFS 1
#define CONFIG_MCONSOLE 1
#define CONFIG_MAGIC_SYSRQ 1
#undef  CONFIG_HOST_2G_2G
#undef  CONFIG_UML_SMP
#undef  CONFIG_SMP
#define CONFIG_CON_ZERO_CHAN "fd:0,fd:1"
#define CONFIG_CON_CHAN "xterm"
#define CONFIG_SSL_CHAN "pty"

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#undef  CONFIG_KMOD

/*
 * Devices
 */
#define CONFIG_BLK_DEV_UBD 1
#undef  CONFIG_BLK_DEV_UBD_SYNC
#undef  CONFIG_BLK_DEV_LOOP
#undef  CONFIG_BLK_DEV_NBD
#undef  CONFIG_BLK_DEV_RAM
#undef  CONFIG_BLK_DEV_INITRD
#undef  CONFIG_MMAPPER
#undef  CONFIG_UML_SOUND
#undef  CONFIG_SOUND
#undef  CONFIG_HOSTAUDIO
#define CONFIG_FD_CHAN 1
#define CONFIG_NULL_CHAN 1
#define CONFIG_PORT_CHAN 1
#define CONFIG_PTY_CHAN 1
#define CONFIG_TTY_CHAN 1
#define CONFIG_XTERM_CHAN 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#undef  CONFIG_NETLINK_DEV
#undef  CONFIG_NETFILTER
#undef  CONFIG_FILTER
#define CONFIG_UNIX 1
#define CONFIG_INET 1
#undef  CONFIG_IP_MULTICAST
#undef  CONFIG_IP_ADVANCED_ROUTER
#undef  CONFIG_IP_PNP
#undef  CONFIG_NET_IPIP
#undef  CONFIG_NET_IPGRE
#undef  CONFIG_ARPD
#undef  CONFIG_INET_ECN
#undef  CONFIG_SYN_COOKIES
#undef  CONFIG_IPV6
#undef  CONFIG_KHTTPD
#undef  CONFIG_ATM
#undef  CONFIG_VLAN_8021Q
#undef  CONFIG_IPX
#undef  CONFIG_ATALK
#undef  CONFIG_DECNET
#undef  CONFIG_BRIDGE
#undef  CONFIG_X25
#undef  CONFIG_LAPB
#undef  CONFIG_LLC
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_ECONET
#undef  CONFIG_WAN_ROUTER
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_HW_FLOWCONTROL

/*
 * QoS and/or fair queueing
 */
#undef  CONFIG_NET_SCHED

/*
 * Network device support
 */
#define CONFIG_UML_NET 1
#define CONFIG_UML_NET_ETHERTAP 1
#define CONFIG_UML_NET_TUNTAP 1
#define CONFIG_UML_NET_SLIP 1
#define CONFIG_UML_NET_DAEMON 1
#define CONFIG_UML_NET_MCAST 1
#define CONFIG_NETDEVICES 1

/*
 * ARCnet devices
 */
#undef  CONFIG_ARCNET
#define CONFIG_DUMMY 1
#undef  CONFIG_BONDING
#undef  CONFIG_EQUALIZER
#define CONFIG_TUN 1
#define CONFIG_ETHERTAP 1

/*
 * Ethernet (10 or 100Mbit)
 */
#undef  CONFIG_NET_ETHERNET

/*
 * Ethernet (1000 Mbit)
 */
#undef  CONFIG_ACENIC
#undef  CONFIG_DL2K
#undef  CONFIG_MYRI_SBUS
#undef  CONFIG_NS83820
#undef  CONFIG_HAMACHI
#undef  CONFIG_YELLOWFIN
#undef  CONFIG_SK98LIN
#undef  CONFIG_FDDI
#undef  CONFIG_HIPPI
#undef  CONFIG_PLIP
#define CONFIG_PPP 1
#undef  CONFIG_PPP_MULTILINK
#undef  CONFIG_PPP_FILTER
#undef  CONFIG_PPP_ASYNC
#undef  CONFIG_PPP_SYNC_TTY
#undef  CONFIG_PPP_DEFLATE
#undef  CONFIG_PPP_BSDCOMP
#undef  CONFIG_PPPOE
#define CONFIG_SLIP 1
#undef  CONFIG_SLIP_COMPRESSED
#undef  CONFIG_SLIP_SMART
#undef  CONFIG_SLIP_MODE_SLIP6

/*
 * Wireless LAN (non-hamradio)
 */
#undef  CONFIG_NET_RADIO

/*
 * Token Ring devices
 */
#undef  CONFIG_TR
#undef  CONFIG_NET_FC
#undef  CONFIG_RCPCI
#undef  CONFIG_SHAPER

/*
 * Wan interfaces
 */
#undef  CONFIG_WAN

/*
 * Multi-device support (RAID and LVM)
 */
#undef  CONFIG_MD
#undef  CONFIG_BLK_DEV_MD
#undef  CONFIG_MD_LINEAR
#undef  CONFIG_MD_RAID0
#undef  CONFIG_MD_RAID1
#undef  CONFIG_MD_RAID5
#undef  CONFIG_MD_MULTIPATH
#undef  CONFIG_BLK_DEV_LVM

/*
 * Kernel hacking
 */
#undef  CONFIG_DEBUG_SLAB
#define CONFIG_DEBUGSYM 1
#define CONFIG_PT_PROXY 1
#undef  CONFIG_GPROF
#undef  CONFIG_GCOV
