#ifndef dvidef_h
#define dvidef_h

#define		DVI$_DEVCHAR		2
#define		DVI$_DEVCLASS		4
#define		DVI$_DEVTYPE		6
#define		DVI$_DEVBUFSIZ		8
#define		DVI$_DEVDEPEND		10
#define		DVI$_UNIT		12
#define		DVI$_PID		14
#define		DVI$_OWNUIC		16
#define		DVI$_VPROT		18
#define		DVI$_ERRCNT		20
#define		DVI$_OPCNT		22
#define		DVI$_RECSIZ		24
#define		DVI$_MAXBLOCK		26
#define		DVI$_DEVDEPEND2		28
#define		DVI$_REFCNT		30
#define		DVI$_DEVNAM		32
#define		DVI$_VOLNAM		34
#define		DVI$_SECTORS		36
#define		DVI$_TRACKS		38
#define		DVI$_CYLINDERS		40
#define		DVI$_FREEBLOCKS		42
#define		DVI$_LOGVOLNAM		44
#define		DVI$_VOLNUMBER		46
#define		DVI$_VOLCOUNT		48
#define		DVI$_ROOTDEVNAM		50
#define		DVI$_NEXTDEVNAM		52
#define		DVI$_TRANSCNT		54
#define		DVI$_MOUNTCNT		56
#define		DVI$_CLUSTER		58
#define		DVI$_MAXFILES		60
#define		DVI$_SERIALNUM		62
#define		DVI$_ACPPID		64
#define		DVI$_ACPTYPE		66
#define		DVI$_CONCEALED		68
#define		DVI$_REC		70
#define		DVI$_CCL		72
#define		DVI$_TRM		74
#define		DVI$_DIR		76
#define		DVI$_SDI		78
#define		DVI$_SQD		80
#define		DVI$_SPL		82
#define		DVI$_OPR		84
#define		DVI$_RCT		86
#define		DVI$_NET		88
#define		DVI$_FOD		90
#define		DVI$_DUA		92
#define		DVI$_SHR		94
#define		DVI$_GEN		96
#define		DVI$_AVL		98
#define		DVI$_MNT		100
#define		DVI$_MBX		102
#define		DVI$_DMT		104
#define		DVI$_ELG		106
#define		DVI$_ALL		108
#define		DVI$_FOR		110
#define		DVI$_SWL		112
#define		DVI$_IDV		114
#define		DVI$_ODV		116
#define		DVI$_RND		118
#define		DVI$_RTM		120
#define		DVI$_RCK		122
#define		DVI$_WCK		124
#define		DVI$_TT_PASSALL		126
#define		DVI$_TT_NOECHO		128
#define		DVI$_TT_NOTYPEAHD	130
#define		DVI$_TT_ESCAPE		132
#define		DVI$_TT_HOSTSYNC	134
#define		DVI$_TT_TTSYNC		136
#define		DVI$_TT_SCRIPT		138
#define		DVI$_TT_LOWER		140
#define		DVI$_TT_MECHTAB		142
#define		DVI$_TT_WRAP		144
#define		DVI$_TT_CRFILL		146
#define		DVI$_TT_LFFILL		148
#define		DVI$_TT_SCOPE		150
#define		DVI$_TT_REMOTE		152
#define		DVI$_TT_EIGHTBIT	154
#define		DVI$_TT_MBXDSABL	156
#define		DVI$_TT_NOBRDCST	158
#define		DVI$_TT_READSYNC	160
#define		DVI$_TT_MECHFORM	162
#define		DVI$_TT_HALFDUP		164
#define		DVI$_TT_MODEM		166
#define		DVI$_TT_OPER		168
#define		DVI$_TT_PAGE		170
#define		DVI$_TT_LOCALECHO	172
#define		DVI$_TT_AUTOBAUD	174
#define		DVI$_TT_HANGUP		176
#define		DVI$_TT_MODHANGUP	178
#define		DVI$_TT_BRDCSTMBX	180
#define		DVI$_TT_DMA		182
#define		DVI$_TT_ALTYPEAHD	184
#define		DVI$_TT_SETSPEED	186
#define		DVI$_TT_DCL_MAILBX	188
#define		DVI$_TT_EDITING		190
#define		DVI$_TT_INSERT		192
#define		DVI$_TT_FALLBACK	194
#define		DVI$_TT_DIALUP		196
#define		DVI$_TT_SECURE		198
#define		DVI$_TT_DISCONNECT	200
#define		DVI$_TT_PASTHRU		202
#define		DVI$_TT_SIXEL		204
#define		DVI$_TT_DRCS		206
#define		DVI$_TT_PRINTER		208
#define		DVI$_TT_APP_KEYPAD	210
#define		DVI$_TT_SYSPWD		212
#define		DVI$_TT_ANSICRT		214
#define		DVI$_TT_REGIS		216
#define		DVI$_TT_BLOCK		218
#define		DVI$_TT_AVO		220
#define		DVI$_TT_EDIT		222
#define		DVI$_TT_DECCRT		224
#define		DVI$_STS		226
#define		DVI$_DEVSTS		228
#define		DVI$_DEVCHAR2		230
#define		DVI$_FULLDEVNAM		232
#define		DVI$_LOCKID		234
#define		DVI$_ALLDEVNAM		236
#define		DVI$_VOLSETMEM		238
#define		DVI$_DEVLOCKNAM		240
#define		DVI$_ALLOCLASS		242
#define		DVI$_ALT_HOST_AVAIL	244
#define		DVI$_ALT_HOST_NAME	246
#define		DVI$_ALT_HOST_TYPE	248
#define		DVI$_HOST_AVAIL		250
#define		DVI$_HOST_COUNT		252
#define		DVI$_HOST_NAME		254
#define		DVI$_HOST_TYPE		256
#define		DVI$_REMOTE_DEVICE	258
#define		DVI$_SERVED_DEVICE	260
#define		DVI$_SHDW_CATCHUP_COPYING	262
#define		DVI$_SHDW_MASTER	264
#define		DVI$_SHDW_MASTER_NAME	266
#define		DVI$_SHDW_MEMBER	268
#define		DVI$_SHDW_MERGE_COPYING	270
#define		DVI$_SHDW_NEXT_MBR_NAME	272
#define		DVI$_TT_PHYDEVNAM	274
#define		DVI$_TT_DECCRT2		276
#define		DVI$_MEDIA_NAME		278
#define		DVI$_MEDIA_TYPE		280
#define		DVI$_MEDIA_ID		282
#define		DVI$_SHDW_FAILED_MEMBER	284
#define		DVI$_MSCP_UNIT_NUMBER	286
#define		DVI$_DISPLAY_DEVNAM	288
#define		DVI$_TT_ACCPORNAM	290
#define		DVI$_DEVDEPEND3		292
#define		DVI$_TT_MULTISESSION	294
#define		DVI$_TT_DECCRT3		296
#define		DVI$_SET_HOST_TERMINAL	298
#define		DVI$_DFS_ACCESS		300
#define		DVI$_DAPDEVNAM		302
#define		DVI$_TT_DECCRT4		304
#define		DVI$_TT_CHARSET		306
#define		DVI$_TT_CS_KANA		308
#define		DVI$_TT_CS_KANJI	310
#define		DVI$_TT_CS_HANZI	312
#define		DVI$_TT_CS_HANGUL	314
#define		DVI$_TT_CS_HANYU	316
#define		DVI$_TT_CS_THAI		318
#define		DVI$_DEVDEPEND4		320
#define		DVI$_DEVICE_TYPE_NAME	322
#define		DVI$_TT_ASIAN_MODE	324
#define		DVI$_PREFERRED_CPU	326
#define		DVI$_TT_DECCRT5		328
#define		DVI$_TT_ANSI_COLOR	330
#define		DVI$_MT3_SUPPORTED	332
#define		DVI$_MT3_DENSITY	334
#define		DVI$_DRIVER_IMAGE_NAME	336
#define		DVI$_CLIENT_DEVICE	338
#define		DVI$_FC_PORT_NAME	340
#define		DVI$_FC_NODE_NAME	342
#define		DVI$_WWID		344
#define		DVI$M_SECONDARY		0x1
#define		DVI$M_NOREDIRECT	0x8000
	
#define		DVI$C_SECONDARY		1
#define		DVI$C_ACP_F11V1		1
#define		DVI$C_ACP_F11V2		2
#define		DVI$C_ACP_MTA		3
#define		DVI$C_ACP_NET		4
#define		DVI$C_ACP_REM		5
#define		DVI$C_ACP_HBS		6
#define		DVI$C_ACP_F11V3		7
#define		DVI$C_ACP_F11V4		8
#define		DVI$C_ACP_F64		9
#define		DVI$C_ACP_UCX		10
#define		DVI$C_ACP_F11V5		11
#define		DVI$C_ACP_F11V6		12
		
struct _dvidef {
  unsigned dvi$v_secondary  : 1;
  unsigned dvi$v_item_code  : 14;
  unsigned dvi$v_noredirect : 1;
};

#endif
