#ifndef LIBDTDEF_H
#define LIBDTDEF_H

#define LIB$K_MONTH_OF_YEAR 1
#define LIB$K_DAY_OF_YEAR 2
#define LIB$K_HOUR_OF_YEAR 3
#define LIB$K_MINUTE_OF_YEAR 4
#define LIB$K_SECOND_OF_YEAR 5
#define LIB$K_DAY_OF_MONTH 6
#define LIB$K_HOUR_OF_MONTH 7
#define LIB$K_MINUTE_OF_MONTH 8
#define LIB$K_SECOND_OF_MONTH 9
#define LIB$K_DAY_OF_WEEK 10
#define LIB$K_HOUR_OF_WEEK 11
#define LIB$K_MINUTE_OF_WEEK 12
#define LIB$K_SECOND_OF_WEEK 13
#define LIB$K_HOUR_OF_DAY 14
#define LIB$K_MINUTE_OF_DAY 15
#define LIB$K_SECOND_OF_DAY 16
#define LIB$K_MINUTE_OF_HOUR 17
#define LIB$K_SECOND_OF_HOUR 18
#define LIB$K_SECOND_OF_MINUTE 19
#define LIB$K_JULIAN_DATE 20
#define LIB$K_DELTA_WEEKS 21
#define LIB$K_DELTA_DAYS 22
#define LIB$K_DELTA_HOURS 23
#define LIB$K_DELTA_MINUTES 24
#define LIB$K_DELTA_SECONDS 25
#define LIB$K_DELTA_WEEKS_F 26
#define LIB$K_DELTA_DAYS_F 27
#define LIB$K_DELTA_HOURS_F 28
#define LIB$K_DELTA_MINUTES_F 29
#define LIB$K_DELTA_SECONDS_F 30
#define LIB$K_MAX_OPERATION 31

#endif /* LIBDTDEF_H */
