#!/bin/sh

unamem=`uname -m`

if [ $unamem = x86_64 ]; then
ARCH=x86_64
else
ARCH=i386
fi

[ -f ../grub/src/build/grub/grub ] || ( echo build grub first; exit 1 )
[ -f ../init/src/init ] || ( echo build init first; exit 1 )

# grub floppy

dd if=/dev/zero count=2880 of=a.img
mke2fs -F a.img
mount -t ext2 -o loop a.img /mnt

mkdir -p /mnt/boot/grub
cp -p grub.conf /mnt/boot/grub
cp -p grub.conf /mnt/boot/grub/menu.lst
[ -f ../grub/src/build/stage1/stage1 ] && cp -p ../grub/src/build/stage?/stage* /mnt/boot/grub

umount /mnt

../grub/src/build/grub/grub --batch --device-map=/dev/null <<EOF
device (fd0) a.img
root (fd0)
setup (fd0)
quit
EOF

# ext2 fs

dd if=/dev/zero count=131072 of=c.img

sfdisk -C 8 -H 255 -S 63 c.img  << EOF
c.img1 : start=        0, size=        4, Id= 83
c.img2 : start=        4, size=        4, Id= 2a
EOF

losetup -o 512 /dev/loop0 c.img

mke2fs -b 1024 /dev/loop0 32130

mount -t ext2 /dev/loop0 /mnt

mkdir /mnt/boot

mkdir -p /mnt/etc

mkdir -p /mnt/vms\$common/sysexe
dd if=/dev/zero count=128 of=/mnt/vms\$common/sysexe/pagefile.sys

umount /mnt
losetup -d /dev/loop0

losetup -o 32901120 /dev/loop0 c.img
../init/src/init /dev/loop0 SYSDISK 64260
losetup -d /dev/loop0

cp -pi c.img c2.img

exit 0

#The rest is something which bugs in the usual versions
#grub --batch <<EOF
#device (hd0) c.img
#geometry (hd0) 4 255 63
#root (hd0)
#setup (hd0)
#quit
#EOF
