#!/bin/sh

unamem=`uname -m`

if [ $unamem == x86_64 ]; then
ARCH=x86_64
else
ARCH=i386
fi

losetup -o 512 /dev/loop0 c.img
mount -t ext2 /dev/loop0 /mnt

cp -p ../linux/arch/${ARCH}/boot/bzImage /mnt/boot/freevms.noiomm

umount /mnt
losetup -d /dev/loop0

losetup -o 512 /dev/loop0 c2.img
mount -t ext2 /dev/loop0 /mnt

cp -p ../linux/arch/${ARCH}/boot/bzImage /mnt/boot/freevms.noiomm

umount /mnt
losetup -d /dev/loop0

