#ifndef i386_autoconf_h
#define i386_autoconf_h

#define CONFIG_IA32_EMULATION 1
#define CONFIG_X86_64 1
#define CONFIG_X86 1
#undef  CONFIG_ISA
#undef  CONFIG_SBUS
#undef  CONFIG_UID16
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#undef  CONFIG_RWSEM_XCHGADD_ALGORITHM
#define CONFIG_X86_CMPXCHG 1
#define ONFIG_EARLY_PRINTK 1

/*
 * Processor type and features
 */
#define CONFIG_GENERIC_CPU 1
#if (defined CONFIG_GENERIC_CPU) || (defined CONFIG_MPSC)
#define CONFIG_X86_L1_CACHE_BYTES (128)
#define CONFIG_X86_L1_CACHE_SHIFT (7)
#else
#define CONFIG_X86_L1_CACHE_BYTES (64)
#define CONFIG_X86_L1_CACHE_SHIFT (6)
#endif
#define CONFIG_X86_TSC 1
#define CONFIG_X86_GOOD_APIC 1
#undef  CONFIG_X86_MSR
#undef  CONFIG_X86_CPUID
#undef  CONFIG_MATH_EMULATION
#undef  CONFIG_EISA
#undef  CONFIG_MCA
#define CONFIG_X86_IO_APIC 1
#define CONFIG_X86_LOCAL_APIC 1
#undef  CONFIG_MTRR
#define CONFIG_SMP 1
#undef  CONFIG_HPET_TIMER
#undef  CONFIG_GART_IOMMU
#undef  CONFIG_SWIOTLB
#ifndef CONFIG_GART_IOMMU
#define CONFIG_DUMMY_IOMMU 1
#endif
#ifndef CONFIG_SMP
#define CONFIG_X86_UP_IOAPIC 1
#endif
#define CONFIG_MCE 1
#ifdef CONFIG_SMP
#undef CONFIG_K8_NUMA
#ifdef CONFIG_K8_NUMA
#define CONFIG_DISCONTIGMEM 1
#define CONFIG_NUMA 1
#endif
#endif

#undef  CONFIG_KCORE_AOUT
#undef  CONFIG_PM
#undef  CONFIG_APM_IGNORE_USER_SUSPEND
#undef  CONFIG_APM_DO_ENABLE
#undef  CONFIG_APM_CPU_IDLE
#undef  CONFIG_APM_DISPLAY_BLANK
#undef  CONFIG_APM_RTC_IS_GMT
#undef  CONFIG_APM_ALLOW_INTS
#undef  CONFIG_APM_REAL_MODE_POWER_OFF

/*
 * General setup
 */
#define CONFIG_PCI 1
#undef  CONFIG_PCI_GOBIOS
#undef  CONFIG_PCI_GODIRECT
#undef  CONFIG_PCI_GOANY
#undef  CONFIG_PCI_BIOS
#define CONFIG_PCI_DIRECT 1
#undef  CONFIG_PCI_NAMES
#undef  CONFIG_PCMCIA
#undef  CONFIG_HOTPLUG_PCI

/*
 * Memory Technology Devices (MTD)
 */
#undef  CONFIG_MTD
/*
 * Block devices
 */
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_PARIDE
#undef  CONFIG_BLK_CPQ_DA
#undef  CONFIG_BLK_CPQ_CISS_DA
#undef  CONFIG_BLK_DEV_DAC960

/*
 * ATA/IDE/MFM/RLL support
 */
#define CONFIG_IDE 1

/*
 * IDE, ATA and ATAPI Block devices
 */
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef  CONFIG_BLK_DEV_HD_IDE
#undef  CONFIG_BLK_DEV_HD
#define CONFIG_BLK_DEV_IDEDISK 1
#define CONFIG_IDEDISK_MULTI_MODE 1
#undef  CONFIG_BLK_DEV_IDEDISK_VENDOR
#undef  CONFIG_BLK_DEV_COMMERIAL
#undef  CONFIG_BLK_DEV_IDECD
#undef  CONFIG_BLK_DEV_IDETAPE
#undef  CONFIG_BLK_DEV_IDEFLOPPY
#undef  CONFIG_BLK_DEV_IDESCSI

/*
 * IDE chipset support/bugfixes
 */
#if 0
#define CONFIG_BLK_DEV_CMD640 1
#undef  CONFIG_BLK_DEV_CMD640_ENHANCED
#undef  CONFIG_BLK_DEV_ISAPNP
#define CONFIG_BLK_DEV_RZ1000 1
#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_IDEPCI_SHARE_IRQ 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#define CONFIG_BLK_DEV_ADMA 1
#undef  CONFIG_BLK_DEV_OFFBOARD
#define CONFIG_IDEDMA_PCI_AUTO 1
#define CONFIG_BLK_DEV_IDEDMA 1
#undef  CONFIG_IDEDMA_PCI_WIP
#undef  CONFIG_BLK_DEV_AEC62XX
#undef  CONFIG_BLK_DEV_ALI15X3
#undef  CONFIG_BLK_DEV_AMD74XX
#undef  CONFIG_BLK_DEV_CMD64X
#undef  CONFIG_BLK_DEV_CY82C693
#undef  CONFIG_BLK_DEV_CS5530
#undef  CONFIG_BLK_DEV_HPT34X
#undef  CONFIG_BLK_DEV_HPT366
#define CONFIG_BLK_DEV_PIIX 1
#define CONFIG_PIIX_TUNING 1
#undef  CONFIG_BLK_DEV_NS87415
#undef  CONFIG_BLK_DEV_OPTI621
#undef  CONFIG_BLK_DEV_PDC202XX
#undef  CONFIG_BLK_DEV_SVWKS
#undef  CONFIG_BLK_DEV_SIS5513
#undef  CONFIG_BLK_DEV_SLC90E66
#undef  CONFIG_BLK_DEV_TRM290
#undef  CONFIG_BLK_DEV_VIA82CXXX
#undef  CONFIG_IDE_CHIPSETS
#define CONFIG_IDEDMA_AUTO 1
#undef  CONFIG_IDEDMA_IVB
#undef  CONFIG_DMA_NONPCI
#define CONFIG_BLK_DEV_IDE_MODES 1
#undef  CONFIG_BLK_DEV_ATARAID
#endif

#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#define CONFIG_IDEDMA_PCI_AUTO 1
#define CONFIG_BLK_DEV_IDEDMA 1
#define CONFIG_IDEDMA_AUTO 1
#define CONFIG_IDEDMA_NEW_DRIVE_LISTINGS 1
#define CONFIG_BLK_DEV_IDE_MODES 1
#define CONFIG_BLK_DEV_PIIX 1
#define CONFIG_PIIX_TUNING 1

/*
 * SCSI support
 */
#undef  CONFIG_SCSI

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY 1
#undef  CONFIG_BONDING
#undef  CONFIG_EQUALIZER
#undef  CONFIG_TUN
#undef  CONFIG_ETHERTAP
/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#undef  CONFIG_HAPPYMEAL
#undef  CONFIG_SUNGEM
#define CONFIG_NET_VENDOR_3COM 1
#undef  CONFIG_EL1
#undef  CONFIG_EL2
#undef  CONFIG_ELPLUS
#undef  CONFIG_EL16
#define CONFIG_EL3 1
#undef  CONFIG_3C515
#define CONFIG_VORTEX 1
#undef  CONFIG_LANCE
#define CONFIG_NET_VENDOR_SMC 1
#define CONFIG_WD80x3 1
#undef  CONFIG_ULTRA
#undef  CONFIG_SMC9194
#undef  CONFIG_NET_VENDOR_RACAL
#undef  CONFIG_AT1700
#define CONFIG_DEPCA 1
#define CONFIG_HP100 1
#define CONFIG_NET_ISA 1
#undef  CONFIG_E2100
#define CONFIG_EWRK3 1
#define CONFIG_EEXPRESS 1
#define CONFIG_EEXPRESS_PRO 1
#define CONFIG_HPLAN_PLUS 1
#define CONFIG_HPLAN 1
#undef  CONFIG_LP486E
#undef  CONFIG_ETH16I
#define CONFIG_NE2000 1
#define CONFIG_NET_PCI 1
#define CONFIG_PCNET32 1
#undef  CONFIG_ADAPTEC_STARFIRE
#undef  CONFIG_AC3200
#undef  CONFIG_APRICOT
#undef  CONFIG_CS89x0
#define CONFIG_TULIP 1
#undef  CONFIG_TULIP_MWI
#undef  CONFIG_TULIP_MMIO
#define CONFIG_DE4X5 1
#undef  CONFIG_DGRS
#undef  CONFIG_DM9102
#define CONFIG_EEPRO100 1
#undef  CONFIG_FEALNX
#undef  CONFIG_NATSEMI
#define CONFIG_NE2K_PCI 1
#define CONFIG_8139CP 1
#define CONFIG_8139TOO 1
#undef  CONFIG_8139TOO_PIO
#undef  CONFIG_8139TOO_TUNE_TWISTER
#undef  CONFIG_8139TOO_8129
#undef  CONFIG_8139_NEW_RX_RESET
#undef  CONFIG_SIS900
#undef  CONFIG_EPIC100
#undef  CONFIG_SUNDANCE
#define CONFIG_TLAN 1
#undef  CONFIG_VIA_RHINE
#define CONFIG_WINBOND_840 1
#undef  CONFIG_NET_POCKET

/*
 * Ethernet (1000 Mbit)
 */
#undef  CONFIG_ACENIC
#undef  CONFIG_DL2K
#undef  CONFIG_NS83820
#undef  CONFIG_HAMACHI
#undef  CONFIG_YELLOWFIN
#undef  CONFIG_SK98LIN
#define CONFIG_E1000
#undef CONFIG_E1000_NAPI

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_SERIAL 1
#define  CONFIG_SERIAL_CONSOLE 1

/*
 * Console drivers
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_VIDEO_SELECT 1
#undef  CONFIG_MDA_CONSOLE

/*
 * Kernel hacking
 */
#define CONFIG_DEBUG_KERNEL 1
#undef  CONFIG_DEBUG_HIGHMEM
#undef  CONFIG_DEBUG_SLAB
#undef  CONFIG_DEBUG_IOVIRT
#define CONFIG_MAGIC_SYSRQ 1
#undef  CONFIG_DEBUG_SPINLOCK
#define CONFIG_DEBUG_BUGVERBOSE 1

#endif
