# File: drivers/net/Makefile
#
# Makefile for the Linux network (ethercard) device drivers.
#

O_TARGET := net.o

export-objs := 
obj-y		:= setup.o

include $(TOPDIR)/Rules.make

clean:
	rm -f core *.o *.a *.s
