#!/bin/sh

doedit() {
ed - linux/arch/um/config << EOF
5,7s/^/#/
w
q
EOF

ed - linux/arch/i386/config << EOF
5,7s/^/#/
w
q
EOF

ed - linux/include/linux/autoconf.h << EOF
5
d
w
q
EOF
}

cd ..

(mkdir freevms386.noiomm; cd freevms386.noiomm; ../freevms/myprescript; cd linux; ./prescript; cd ..; doedit; make symlinks; make linux/include/linux/compile.h)

(mkdir freevmsuml.noiomm; cd freevmsuml.noiomm; ../freevms/myprescript; cd linux; ./prescript; cd ..; doedit; make symlinks ARCH=um; make linux/include/linux/compile.h ARCH=um)

(mkdir freevms386.iomm; cd freevms386.iomm; ../freevms/myprescript; cd linux; ./prescript; cd ..; make symlinks; make linux/include/linux/compile.h)

(mkdir freevmsuml.iomm; cd freevmsuml.iomm; ../freevms/myprescript; cd linux; ./prescript; cd ..; make symlinks ARCH=um; make linux/include/linux/compile.h ARCH=um)

cd freevms
