#!/bin/sh

doedit() {
ed - linux/arch/um/config << EOF
5,7s/^/#/
w
q
EOF

ed - linux/arch/i386/config << EOF
5,7s/^/#/
w
q
EOF

ed - linux/arch/x86_64/config << EOF
5,7s/^/#/
w
q
EOF

ed - linux/include/linux/autoconf.h << EOF
5
d
w
q
EOF
}

cd ..

unamem=`uname -m`

if [ $unamem = x86_64 ]; then

(mkdir freevmsx86_64.iomm; cd freevmsx86_64.iomm; ../freevms/myprescript; cd linux; ./prescript; cd ..; make symlinks; make linux/include/linux/compile.h)

else

(mkdir freevms386.iomm; cd freevms386.iomm; ../freevms/myprescript; cd linux; ./prescript; cd ..; make -f Makefile.kernel symlinks; make -f Makefile.kernel linux/include/linux/compile.h)

fi

cd freevms
