#!/bin/sh
CFLAGS=
CPPFLAGS=
unamem=`uname -m`
if [ $unamem != x86_64 ]; then
CC=gcc
else
CC=gcc
LDFLAGS=-static
LIBS=
fi
rm -rf grub-0.95
tar xzf grub-0.95.tar.gz
cd grub-0.95
patch -p1 < ../../../subprojects/grub-0.95-diff1
cd ..
mkdir build
cd build
../grub-0.95/configure --enable-ext2fs --enable-ods2
make
cd ..
