# $Id$
# $Locker$

all: all.cld

install: all
	install -d ../../rootum/vms"$$"common/sysexe
	install -d ../../rooti386/vms"$$"common/sysexe
	install *.cld ../../rootum/vms"$$"common/sysexe/
	install *.cld ../../rooti386/vms"$$"common/sysexe
