struct HM2$ {
unsigned int HM2$L_HOMELBN;
unsigned int HM2$L_ALHOMELBN;
unsigned int HM2$L_ALTIDXLBN;
unsigned char HM2$W_STRUCLEV[2];
unsigned short int HM2$W_CLUSTER;
unsigned short int HM2$W_HOMEVBN;
unsigned short int HM2$W_ALHOMEVBN;
unsigned short int HM2$W_ALTIDXVBN;
unsigned short int HM2$W_IBMAPVBN;
unsigned int  HM2$L_IBMAPLBN;
unsigned int HM2$L_MAXFILES;
unsigned short int HM2$W_IBMAPSIZE;
unsigned char HM2$W_RESFILES[2];
unsigned char HM2$W_DEVTYPE[2];
unsigned char HM2$W_RVN[2];
unsigned char HM2$W_SETCOUNT[2];
unsigned char HM2$W_VOLCHAR[2];
unsigned char HM2$L_VOLOWNER[4];
unsigned char dummy1[4];
unsigned char HM2$W_PROTECT[2];
unsigned char HM2$W_FILEPROT[2];
unsigned char dummy2[2];
unsigned short int HM2$W_CHECKSUM1;
unsigned char HM2$Q_CREDATE[8];
unsigned char HM2$B_WINDOW[1];
unsigned char HM2$B_LRU_LIM;
unsigned char HM2$W_EXTEND[2];
unsigned char HM2$Q_RETAINMIN[8];
unsigned char HM2$Q_RETAINMAX[8];
unsigned char HM2$Q_REVDATE[8];
unsigned char HM2$R_MIN_CLASS[20];
unsigned char HM2$R_MAX_CLASS[20];
unsigned char dummy3[320];
unsigned char HM2$L_SERIALNUM[4];
unsigned char HM2$T_STRUCNAME[12];
unsigned char HM2$T_VOLNAME[12];
unsigned char HM2$T_OWNERNAME[12];
unsigned char HM2$T_FORMAT[12];
unsigned char dummy4[2];
unsigned short int HM2$W_CHECKSUM2;
};
