#ifndef dyndef_h
#define dyndef_h

/* Author: Roar Thronæs */

#define DYN$C_ADB         1
#define DYN$C_ACB         2
#define DYN$C_AQB         3
#define DYN$C_CEB         4
#define DYN$C_CRB         5
#define DYN$C_DDB         6
#define DYN$C_FCB         7
#define DYN$C_FRK         8
#define DYN$C_IDB         9
#define DYN$C_IRP         10
#define DYN$C_LOG         11
#define DYN$C_PCB         12
#define DYN$C_PQB         13
#define DYN$C_RVT         14
#define DYN$C_TQE         15
#define DYN$C_UCB         16
#define DYN$C_VCB         17
#define DYN$C_WCB         18
#define DYN$C_BUFIO         19
#define DYN$C_TYPAHD         20
#define DYN$C_GSD         21
#define DYN$C_MVL         22
#define DYN$C_NET         23
#define DYN$C_KFE         24
#define DYN$C_MTL         25
#define DYN$C_BRDCST         26
#define DYN$C_CXB         27
#define DYN$C_NDB         28
#define DYN$C_SSB         29
#define DYN$C_DPT         30
#define DYN$C_JPB         31
#define DYN$C_PBH         32
#define DYN$C_PDB         33
#define DYN$C_PIB         34
#define DYN$C_PFL         35
#define DYN$C_PFLMAP         36
#define DYN$C_PTR         37
#define DYN$C_KFRH         38
#define DYN$C_DCCB         39
#define DYN$C_EXTGSD         40
#define DYN$C_SHMGSD         41
#define DYN$C_SHB         42
#define DYN$C_MBX         43
#define DYN$C_IRPE         44
#define DYN$C_SLAVCEB         45
#define DYN$C_SHMCEB         46
#define DYN$C_JIB         47
#define DYN$C_TWP         48
#define DYN$C_RBM         49
#define DYN$C_VCA         50
#define DYN$C_CDB         51
#define DYN$C_LPD         52
#define DYN$C_LKB         53
#define DYN$C_RSB         54
#define DYN$C_LKID         55
#define DYN$C_RSHT         56
#define DYN$C_CDRP         57
#define DYN$C_ERP         58
#define DYN$C_CIDG         59
#define DYN$C_CIMSG         60
#define DYN$C_XWB         61
#define DYN$C_WQE         62
#define DYN$C_ACL         63
#define DYN$C_LNM         64
#define DYN$C_FLK         65
#define DYN$C_RIGHTSLIST         66
#define DYN$C_KFD         67
#define DYN$C_KFPB         68
#define DYN$C_CIA         69
#define DYN$C_PMB         70
#define DYN$C_PFB         71
#define DYN$C_CHIP         72
#define DYN$C_ORB         73
#define DYN$C_QVAST         74
#define DYN$C_MVWB         75
#define DYN$C_UNC         76
#define DYN$C_DCB         77
#define DYN$C_DLL         78
#define DYN$C_SPL         79
#define DYN$C_ARB         80
#define DYN$C_SUBTYPE       96
#define DYN$C_SCS           96
#define DYN$C_CI         97
#define DYN$C_LOADCODE         98
#define DYN$C_INIT         99
#define DYN$C_CLASSDRV         100
#define DYN$C_CLU         101
#define DYN$C_PGD         102
#define DYN$C_DECW         103
#define DYN$C_VWS         104
#define DYN$C_DSRV         105
#define DYN$C_MP         106
#define DYN$C_NSA         107
/*
#define DYN$C_CWPS         108
#define DYN$C_         109
#define DYN$C_         110
#define DYN$C_         111
#define DYN$C_         112
#define DYN$C_         113
#define DYN$C_         114
#define DYN$C_         115
#define DYN$C_         116
#define DYN$C_         117
#define DYN$C_         118
#define DYN$C_         119
#define DYN$C_         120
#define DYN$C_         121
#define DYN$C_         122
#define DYN$C_         123
#define DYN$C_         124
#define DYN$C_         125
#define DYN$C_         126
#define DYN$C_         127
*/
#define DYN$C_SHRBUFIO         128

#define DYN$C_SCS_CDL 1
#define DYN$C_SCS_CDT 2
#define DYN$C_SCS_DIR 3
#define DYN$C_SCS_PB 4
#define DYN$C_SCS_PDT 5
#define DYN$C_SCS_RDT 6
#define DYN$C_SCS_SB 7
#define DYN$C_SCS_SPPB 8
#define DYN$C_SCS_SPNB 9
#define DYN$C_SCS_SBNB 10
#define DYN$C_SCS_PLVEC 11
#define DYN$C_SCS_PDTLIST 12
#define DYN$C_SCS_BD 13
#define DYN$C_SCS_CMNBDLT 14
#define DYN$C_SCS_RBUN 15
#define DYN$C_SCS_CRRR 16
#define DYN$C_SCS_TYP1 17

#endif
