# $Id$
# $Makefile$

#all: libqueue.a

#libqueue.a: queue.o
#	ar cr $@ queue.o
#	ranlib $@ 

#queue.o: queue.c
#	gcc -c queue.c -I.

O_TARGET := pal.o

obj-y	= ast.o ipl.o queue.o 

include $(TOPDIR)/Rules.make