#!/bin/sh
ncftpget ftp://ftp.nvg.ntnu.no/pub/vms/bliss/bliss-0_211.tgz
ncftpget ftp://ftp.nvg.ntnu.no/pub/vms/freevms/gcc-vmscall-0_3_11.tar.gz
ncftpget ftp://ftp.gnu.org/pub/gnu/gcc/gcc-4.2.1/gcc-core-4.2.1.tar.bz2
