#!/bin/sh

LIBS=

unamem=`uname -m`

if [ $unamem = x86_64 ]; then
ARCH=x86_64
LIBS=
else
ARCH=i386
fi

CFLAGS=
CPPFLAGS=
CC=
rm -rf gcc-4.2.1
bunzip2 -dc gcc-core-4.2.1.tar.bz2|tar xpf -
tar xzf gcc-vmscall-0_3_11.tar.gz
patch -p1 < gcc-vmscall/gcc-4.2.1-vmscall.patch
rm bliss
ln -sf gcc-4.2.1 bliss
tar xzf bliss-0_211.tgz
rm -rf build
mkdir build
cd build
if [ $unamem = x86_64 ]; then
../gcc-4.2.1/configure --enable-languages=bliss --with-included-gettext  --prefix=$TOPDIR/bliss --disable-multilib 
else
../gcc-4.2.1/configure --enable-languages=bliss --with-included-gettext --prefix=$TOPDIR/bliss
fi
make bootstrap
make install
cd ..
