#!/bin/sh
CFLAGS=
CPPFLAGS=
CC=
rm -rf gcc-3.4.3
bunzip2 -dc gcc-3.4.3.tar.bz2|tar xpf -
ln -sf gcc-3.4.3 bliss
tar xzf bliss-0_011.tgz
rm -rf build
mkdir build
cd build
../gcc-3.4.3/configure --enable-languages=bliss --with-included-gettext --prefix=$TOPDIR/bliss
make bootstrap
make install
cd ..
