#!/bin/bash

	(cd arch; ln -s ../../freevms .)
	mkdir -p include/asm-um arch/um/{kernel,lib,mm,include}
	(cd ../freevms/starlet/src; ln -s sys\$routines.h sysoutines.h)
	(cd ../freevms/starlet/src; ln -s lib\$routines.h liboutines.h)
	(cd ../freevms/starlet/src; ln -s cli\$routines.h clioutines.h)
	(cd ../freevms/starlet/src; ln -s lbr\$routines.h lbroutines.h)

for X in `cd ../freevms/linux; find . \( -name CVS -prune \) -o -type f`; do
	[ -f $X ] && rm $X
	[ -f ../freevms/linux/$X ] && cp -p ../freevms/linux/$X $X;
done
	rm -rf include/asm-um arch/um/{kernel,lib,mm,include}

(cd kernel; 	ln -s ../../freevms/sys/src/syssetpri.c .;
		ln -s ../../freevms/sys/src/syspcntrl.c; 
		ln -s ../../freevms/sys/src/rse.c .;
		ln -s ../../freevms/sys/src/system_data_cells.c .;
		ln -s ../../freevms/sys/src/timeschdl.c .;
		ln -s ../../freevms/sys/src/exsubrout.c .;
		ln -s ../../freevms/sys/src/syswait.c .;
		ln -s ../../freevms/sys/src/sysevtsrv.c .;
		ln -s ../../freevms/sys/src/exception_init.c .;
		ln -s ../../freevms/sys/src/postef.c .;
		ln -s ../../freevms/sys/src/iociopost.c .;
		ln -s ../../freevms/sys/src/astdel.c;
		ln -s ../../freevms/sys/src/forkcntrl.c .;
		ln -s ../../freevms/sys/src/iosubnpag.c .;
		ln -s ../../freevms/sys/src/sysastcon.c .;
		ln -s ../../freevms/sys/src/sysgettim.c .;
		ln -s ../../freevms/sys/src/syssetime.c .;
		ln -s ../../freevms/sys/src/syscvrtim.c .;
		ln -s ../../freevms/sys/src/sysschevt.c .;
		ln -s ../../freevms/sys/src/syscanevt.c .;
		ln -s ../../freevms/sys/src/sysdelprc.c .;
		ln -s ../../freevms/sys/src/sysforcex.c .;
		ln -s ../../freevms/sys/src/sysexit.c .;
		ln -s ../../freevms/sys/src/syssetmod.c .;
		ln -s ../../freevms/sys/src/sysenqdeq.c .;
		ln -s ../../freevms/sys/src/sysqioreq.c .;
		ln -s ../../freevms/sys/src/sysqiofdt.c .;
		ln -s ../../freevms/sys/src/sysacpfdt.c .;
		ln -s ../../freevms/sys/src/sysassign.c .;
		ln -s ../../freevms/sys/src/sysdassgn.c .;
		ln -s ../../freevms/sys/src/iosubpagd.c .;
		ln -s ../../freevms/sys/src/sysgetlki.c .;
		ln -s ../../freevms/sys/src/syslnm.c .;
		ln -s ../../freevms/sys/src/lnmsub.c .;
		ln -s ../../freevms/driver/src/random.c .;
		ln -s ../../freevms/driver/src/dudriver.c .;
		ln -s ../../freevms/mscp/src/mscp.c .;
		ln -s ../../freevms/sysloa/src/sys_scs.c .;

		rm ipl.c; ln -s ../../freevms/pal/src/ipl.c .;
		rm ast.c; ln -s ../../freevms/pal/src/ast.c .;
)

echo you have read the HOWTO and done a make in ../freevms?
